usethis::use_build_ignore("dev_history.r")
usethis::use_build_ignore("old")
usethis::use_build_ignore("essais")
usethis::use_build_ignore("essais_contribs.Rmd")
usethis::use_build_ignore("rcpp_test")
usethis::use_build_ignore("essais_md.Rmd")

usethis::use_gpl3_license("Anissa Saumtally")
usethis::use_package("assertthat")
usethis::use_package("Deriv",type = "Depends")
usethis::use_package("splitstackshape")
usethis::use_package("purrr")
usethis::use_package("methods")
usethis::use_package("dplyr",type = "Depends")
usethis::use_package("stringr")
usethis::use_package("tidyr")
usethis::use_package("scales")
usethis::use_package("gsubfn")
usethis::use_package("ggplot2")
usethis::use_package("Matrix")
usethis::use_package("stats")
usethis::use_package("cointReg")
usethis::use_package("x12",type = "Suggests")
usethis::use_package("lubridate",type = "Suggests")
usethis::use_package("rdbnomics",type = "Suggests")

use_vignette("GuideUtilisateur")
devtools::build()

usethis::use_data_raw('functions_supported')
thorbeta::create.model("old_algo" , model_source = "essais/opale_prevision.txt",model_path = "essais/",quick_compile = FALSE)

