#' Plot simulated vs observed
#'
#' @param sim_obs_data data.frame generated by simulate_equation() or dyn_contrib()
#' @param title Title of the graph
#' @param type one of 'g' (growth rate), 'dlog' (diff(log)), 'd' (diff) or 'lvl'  (level)
#' @param colours vector of two colours. Default : c("navyblue","darkorange3")
#' @param start_plot which date should the plot start. Must be in index time. The subdata must not contain NAs.
#' @param end_plot end date, must be in index time. The subdata must not contain NAs.
#' @param index_time Name of the column which contains the time info. By default is NULL and takes the first column of sim_obs_data
#' @import ggplot2
#' @return a ggplot graph
#' @export
#'
graph_sim_obs<-function(sim_obs_data,start_plot=NULL, end_plot= NULL,index_time= NULL, title = "",type= c("g","dlog",'d',"lvl"), colours = c("navyblue","darkorange3") ){
  if(class(sim_obs_data)!="data.frame"){stop("sim_obs_data must be a data.frame generated by simulate_equation() or dyn_contrib()")}

  if(class(title)!="character"){stop("Title must be character string")}

  if(is.null(index_time)){index_time<-colnames(sim_obs_data)[1]}

  if(!index_time %in% colnames(sim_obs_data)){stop('index_time must be a variable of sim_obs_data.')}
  if(!type[1] %in% c("g","dlog",'d',"lvl")){stop("type must be one of 'g' (growth rate), 'dlog' (diff(log)), 'd' (diff) or 'lvl'  (level)")}

  if(!is.null(start_plot)){if(!start_plot %in% sim_obs_data[,index_time]){stop("start_plot must be an element of index_time.")}}
  if(!is.null(end_plot)){if(!end_plot %in% sim_obs_data[,index_time]){stop("end_plot must be an element of index_time.")}}

  if(is.null(start_plot)){start_plot <- head(sim_obs_data[,index_time],1)}
  if(is.null(end_plot)){end_plot <- tail(sim_obs_data[,index_time],1)}


  if(start_plot > end_plot){stop("start_plot must be before end_plot.")}

  if(length(colours)!=2){stop("exactly two colours must be provided")}

  graph_data<- sim_obs_data[which(sim_obs_data[,index_time]>=start_plot & sim_obs_data[,index_time]<=end_plot),]

  #length checks on other vars
  if(type[1]=="g"){
    graph_data$Observed = graph_data$g_obs *100
    graph_data$Simulated = graph_data$g_sim*100
    names_axis= "growth rate in %"
  }
  if(type[1]=="dlog"){
    graph_data$Observed = graph_data$dlog_obs*100
    graph_data$Simulated = graph_data$dlog_sim*100
    names_axis= "growth rate in % (diff(logs))"
  }
  if(type[1]=="d"){
    graph_data$Observed = graph_data$d_obs
    graph_data$Simulated = graph_data$d_sim
    names_axis= "absolute difference"
  }
  if(type[1]=="lvl"){
    graph_data$Observed = graph_data$observed
    graph_data$Simulated = graph_data$simulated
    names_axis= "levels"
  }
  plop = c(1:nrow(graph_data))

  if(sum(is.na(graph_data))>0){stop("The selected time frame contains NAs, please modify start_plot and end_plot parameters for the graph.")}

  if(inherits(graph_data[,index_time],"Date")){
    graph_data[,index_time]<-reformat_date(graph_data[,index_time])
  }

  n_obs<-nrow(graph_data)

  if(n_obs>=14){
    angle_date <- 90
  }else{
    angle_date <- 0}


  if(is.numeric(graph_data[,index_time])){graph_data[,index_time]<-as.character(graph_data[,index_time])}

  ggplot(data=graph_data,aes(x = plop)) +
    geom_line(aes(y = Observed,color = "Observed"),size=1 ) +
    geom_line(aes(y = Simulated ,color = "Simulated"),size=1 )+
    scale_colour_manual("", breaks = c("Observed", "Simulated"),values=colours)+theme_light() +
    theme(legend.position="bottom",axis.text.x = element_text(angle = angle_date),panel.border = element_rect(colour = "black", fill=NA, size=1) )+scale_x_discrete(name ="" ,limits = graph_data[,index_time])+scale_y_continuous(name = names_axis)+ ggtitle(title)

}


#' Draw contributions graph
#'
#' @param contrib_data database generated by dyn_contrib or the annualised version from yearly_contrib
#' @param start_plot start date, must be in index time. The subdata must not contain NAs.
#' @param end_plot end date, must be in index time. The subdata must not contain NAs.
#' @param index_time Name of the column which contains the time info.
#' @param title Title of the graph
#' @param name_endogenous Name of the endogenous variables represented by dlog_obs(.y) for display only.Default : "main variable"
#' @param colours_bar Vector of colours to customize the contrib bars, must be at least the number of contrib variables. The last colour is always the residual colour. If not enough colours are provided, default colours will be used instead. Default: NULL.
#' @param colour_line One colour to customize the line colour. Default: "black".
#' @param legend_n_row Numeric. Number of rows the legend should be spread over. Enables customizing of the display so that the legend fits different sizes of the panel, especially when specifying different longer labels. Default: 2
#' @param bar_labels Character vector to rename the contribution variables in the legend. The order must match the order of variables in the contrib database, with the exception of the residual which must be specified last. If the wrong number of labels is supplied, labels revert to the default ones.  Default: NULL.
#'
#' @import ggplot2
#' @importFrom tidyr pivot_longer
#' @importFrom scales percent_format
#' @importFrom stringr str_replace_all
#' @import dplyr
#' @import purrr
#' @return a ggplot graph
#' @export
#'
graph_contrib<-function(contrib_data,start_plot=NULL,end_plot=NULL,index_time=NULL,title ="Contributions dynamiques" ,name_endogenous="main variable",colour_line="black",colours_bar=NULL,bar_labels=NULL,legend_n_row=2){

  if(is.null(name_endogenous)){name_endogenous<-"dlog_obs"}
  if(is.null(index_time)){index_time<-colnames(contrib_data)[1]}
  test_frequency<-names(contrib_data[grep("residual\\.contrib",names(contrib_data))])
  if(purrr::is_empty(test_frequency)){stop('The database must come from the dyn_contribs or yearly_contribs functions.')}
  if(grepl("\\.y$",test_frequency)==TRUE){yearly_data <- TRUE}else{yearly_data <- FALSE}
  if(yearly_data == TRUE){index_time <- "year"}
  if(yearly_data == FALSE & is.null(index_time)){stop("Please specify the name of the date column in index_time when using not yearly data generated by yearly_contribs().")}else{if (yearly_data == FALSE){
    if(!index_time %in% names(contrib_data)){stop("The variable specified in index_time must be in the contrib_data database.")}
  }
  }

  if(!is.null(start_plot)){if(!start_plot %in% contrib_data[,index_time]){stop("start_plot must be an element of index_time.")}}
  if(!is.null(end_plot)){if(!end_plot %in% contrib_data[,index_time]){stop("end_plot must be an element of index_time.")}}

  if(is.null(start_plot)){start_plot <- head(contrib_data[,index_time],1)}
  if(is.null(end_plot)){end_plot <- tail(contrib_data[,index_time],1)}

  if(start_plot > end_plot){stop("start_plot must be before end_plot.")}
  contrib_data$plop0 <- c(1:nrow(contrib_data))
  start_plot.plop0<- which(contrib_data[,index_time]==start_plot)
  end_plot.plop0<- which(contrib_data[,index_time]==end_plot)


  data_graph<-contrib_data %>% select(grep(paste0("^",index_time,"$|\\.contrib(\\.y)?$|^dlog_obs"),names(contrib_data)),plop0 ) %>% filter(plop0 >=start_plot.plop0) %>% filter(plop0 <=end_plot.plop0)

  if(yearly_data == TRUE){data_graph<-data_graph %>% mutate_if(is.numeric,function(x){x/100})}

  data_graph$plop0<-NULL

  data_graph$plop = c(1:nrow(data_graph))

  if(inherits(data_graph[,index_time],"Date")){
    data_graph[,index_time]<-reformat_date(data_graph[,index_time])
  }

  if(sum(is.na(data_graph))>0){stop("The selected time frame contains NAs, please modify start_plot and end_plot parameters for the graph.")}

  var_bar <- names(data_graph[grep('\\.contrib(\\.y)?$',names(data_graph))])
  n_bars<- length(var_bar)-1

  data_bar <- data_graph[,c(index_time,"plop",var_bar)] %>% tidyr::pivot_longer(all_of(var_bar),"variable" )
  data_bar$variable<- gsub("\\.contrib(\\.y)?$","",data_bar$variable)

  bar_order<-c(var_bar[grep("residual.contrib",var_bar)],var_bar[-grep("residual.contrib",var_bar)])
  bar_order<- gsub("\\.contrib(\\.y)?$","",bar_order)


   if (!is.null(bar_labels)) {
     l_bl<- length(bar_labels)
     if ((l_bl == (n_bars + 1)) &
         is.character(bar_labels)) {
       bar_order_bis<-c(bar_labels[l_bl],bar_labels[1:n_bars])
       bar_order_legend <- bar_labels

       data_bar$variable<-stringr::str_replace_all(data_bar$variable,paste0("^",bar_order,"$"),paste0(bar_order_bis))

       bar_order<-bar_order_bis
     }
   }else{
     bar_order_legend <-
       c(var_bar[-grep("residual.contrib", var_bar)], var_bar[grep("residual.contrib", var_bar)])
     bar_order_legend <- gsub("\\.contrib(\\.y)?$", "", bar_order_legend)
   }

  thor_palette<- c("blue3","turquoise3",
                   "palevioletred3","gold","darkorange","firebrick3",
                   "springgreen4","deeppink4","sienna4","yellowgreen",
                   "peachpuff3","indianred3")


  if (length(colours_bar) >= length(var_bar)) {
    colour_vec <- c(colours_bar[1:n_bars],tail(colours_bar,1))
  } else{
    if (n_bars <= length(thor_palette)) {
      colour_vec <- c(head(thor_palette, n_bars), "grey76")
    } else{
      colour_vec <- c(palette(rainbow(n_bars)), "grey76")
    }
  }
  if(yearly_data ==TRUE){data_graph$observed_var<-data_graph$dlog_obs.y
  data_graph$year<-as.character(data_graph$year*100)
  }else{data_graph$observed_var<-data_graph$observed_var<-data_graph$dlog_obs}

  if(max(abs(data_graph$observed_var))>0.015){
    break_seq <- seq(-100,100,0.01)
  }else{ break_seq <- seq(-100,100,0.0025)}
  n_obs<-nrow(data_graph)

  if(n_obs>=14){
    angle_date <- 90
  }else{
    angle_date <- 0}

  ggplot() +
    geom_bar(data = data_bar, aes(fill=factor(variable,levels=bar_order), y=value, x=plop),position="stack", stat="identity",width = 0.5 )  +
    geom_line(data=data_graph,aes(y = observed_var, x = plop, color= name_endogenous)) +
    scale_color_manual(values = c( colour_line)) +
    labs(color = '') +
    scale_x_discrete(name = "",limits = data_graph[,index_time]) +
    scale_y_continuous(name = "",labels = scales::percent_format(accuracy = 0.25),breaks=break_seq, minor_breaks = break_seq )+

    ggtitle(paste(title))+

    theme(legend.position="bottom" ,axis.text.x = element_text(angle = angle_date),panel.border = element_rect(colour = "grey78", fill=NA, size=1),panel.background = element_rect(fill = 'white', colour = 'grey78'),panel.grid = element_line(color="grey89") )+


    scale_fill_manual(values=colour_vec,name = "",breaks=bar_order_legend) +
    geom_hline(yintercept = 0,color = "grey16")+
    guides(color = guide_legend(nrow = 1, order = 1) ,
      fill = guide_legend(nrow = legend_n_row, order = 2))


}

